#!/bin/bash

#############################################################
# SSH Key Deployer Script
# Purpose: Deploy SSH keys to multiple servers automatically.
# Author: samiulAsumel
#############################################################

set -eou pipefail

# Color codes for output formatting
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
KEY_DIR="$HOME/.ssh"
LOG_FILE="$HOME/ssh-deployment-$(date +%Y%m%d-%H%M%S).log"

# Server inventory (Format: nickname:hostname:user:keyname)
SERVERS=(
	"dev-web:192.168.56.11:devops:techcorp_dev_rsa"
	"dev-db:192.168.56.12:devops:techcorp_dev_rsa"
	"stage-web:192.168.56.21:devops:techcorp_stage_rsa"
	"stage-db:192.168.56.22:devops:techcorp_stage_rsa"
	"prod-web:192.168.56.31:devops:techcorp_prod_rsa"
	"prod-db:192.168.56.32:devops:techcorp_prod_rsa"
)

# Functions
log_message() {
	local level=$1
	shift
	local message="$*"
	echo "[$(date +'%Y-%m-%d %H:%M:%S')] [$level] $message" | tee -a "$LOG_FILE"
}

print_header() {
	echo -e "${BLUE}========================================${NC}"
	echo -e "${BLUE}      SSH Key Deployer Script          ${NC}"
	echo -e "${BLUE}========================================${NC}"
}

check_prerequisites() {
	log_message "INFO" "Checking prerequisites..."

	# Check if ssh-copy-id exists
	if ! command -v ssh-copy-id &> /dev/null; then
		log_message "ERROR" "ssh-copy-id command not found. Please install OpenSSH client tools."
		exit 1
	fi

	# Check if SSH directory exists
	if [[ ! -d "$KEY_DIR" ]]; then
		log_message "ERROR" "SSH directory $KEY_DIR does not exist."
		exit 1
	fi

	log_message "INFO" "All prerequisites met."
}

deploy_key_to_server() {
	local nickname=$1
	local hostname=$2
	local username=$3
	local keyname=$4

	local public_key_path="${KEY_DIR}/${keyname}.pub"
	local local_private_key_path="${KEY_DIR}/${keyname}"

	# Verify key files exist
	if [[ ! -f "$public_key_path" ]]; then
		log_message "ERROR" "Public key $public_key_path not found for $nickname."
		return 1
	fi

	if [[ ! -f "$local_private_key_path" ]]; then
		log_message "ERROR" "Private key $local_private_key_path not found for $nickname."
		return 1
	fi

	log_message "INFO" "Deploying key to $nickname ($hostname)..."

	# Deploy key using ssh-copy-id
	if ssh-copy-id -i "$public_key_path" -o StrictHostKeyChecking=no "$username@$hostname" &>> "$LOG_FILE"; then
		log_message "INFO" "Successfully deployed key to $nickname."
	else
		log_message "ERROR" "Failed to deploy key to $nickname."
		return 1
	fi

	# Test Connection
	if ssh -o BatchMode=yes -o ConnectTimeout=5 -o StrictHostKeyChecking=no -i "$local_private_key_path" "$username@$hostname" 'echo "Connection successful."' &>> "$LOG_FILE"; then
		log_message "INFO" "Connection test to $nickname successful."
	else
		log_message "ERROR" "Connection test to $nickname failed."
		return 1
	fi

	log_message "INFO" "Key deployment to $nickname completed."
	return 0
}

generate_ssh_config() {
	local config_file="${KEY_DIR}/config"
	local backup_file="${config_file}.bak_$(date +%Y%m%d-%H%M%S)"

	log_message "INFO" "Generating SSH config file at $config_file..."

	# Backup existing config
	if [[ -f "$config_file" ]]; then
		cp "$config_file" "$backup_file"
		log_message "INFO" "Existing SSH config backed up to $backup_file."
	fi

	# Generate new config
	{
		echo "# SSH Config generated by SSH Key Deployer script"
		echo "# Generated on $(date)"
		echo ""
		echo "Host *"
		echo "	StrictHostKeyChecking no"
		echo "	UserKnownHostsFile=/dev/null"
		echo "	ServerAliveInterval 60"
		echo "	ServerAliveCountMax 5"
		echo "	Compression yes"
		echo ""

		for server in "${SERVERS[@]}"; do
			IFS=':' read -r nickname hostname username keyname <<< "$server"
			echo "Host $nickname"
			echo "	HostName $hostname"
			echo "	User $username"
			echo "	IdentityFile ${KEY_DIR}/${keyname}"
			echo "	Port 22"
			echo ""
		done
	} > "$config_file"

	chmod 600 "$config_file"
	log_message "INFO" "SSH config file generated successfully."
}

display_summary() {
	local success=$1
	local failure=$2

	echo ""
	echo -e "${BLUE}========================================${NC}"
	echo -e "${GREEN}      Deployment Summary          ${NC}"
	echo -e "Successful deployments: ${GREEN}$success${NC}"
	echo -e "Failed deployments: ${RED}$failure${NC}"
	echo -e "Log file: ${YELLOW}$LOG_FILE${NC}"
	echo -e "${BLUE}========================================${NC}"
}

# Main Script Execution
main() {
	print_header
	check_prerequisites

	local success_count=0
	local failure_count=0

	echo ""
	echo -e "${YELLOW}Starting key deployment to ${#SERVERS[@]} servers...${NC}"
	echo ""

	for server in "${SERVERS[@]}"; do
		IFS=':' read -r nickname hostname username keyname <<< "$server"

		if deploy_key_to_server "$nickname" "$hostname" "$username" "$keyname"; then
			((success_count++))
		else
			((failure_count++))
		fi
		echo ""
	done

	generate_ssh_config
	display_summary "$success_count" "$failure_count"

	if [[ $failure_count -eq 0 ]]; then
		log_message "INFO" "SSH Key Deployment completed successfully for all servers."
	else
		log_message "WARNING" "SSH Key Deployment completed with some failures."
	fi
}

# Run main function
main